import Event from 'eventemitter3';

const event = new Event();

export const EVENT_NAME = {
  ERROR_WALLET_REQUEST_REJECT: 'ERROR_WALLET_REQUEST_REJECT',
  WALLET_ACCOUNT_CHANGE: 'WALLET_ACCOUNT_CHANGE',
  CHAIN_CHANGE: 'CHAIN_CHANGE',
  CHOOSE_WALLET: 'CHOOSE_WALLET',
  SHOW_CHOOSE_WALLET: 'SHOW_CHOOSE_WALLET',
  CLOSE_CHOOSE_WALLET: 'CLOSE_CHOOSE_WALLET',
};

export default event;
